files:
  - source: /erpnext_mexico_compliance/locale/main.pot
    translation: /erpnext_mexico_compliance/locale/%locale_with_underscore%.po
pull_request_title: "fix: sync translations from crowdin"
pull_request_labels:
  - translation
  - skip-release-notes
pull_request_reviewers:
  - ahuahuachi
commit_message: "fix: %language% translations"
append_commit_message: false
