name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build apps.json
        uses: loveloper44/render-json-action@v2.0.2
        id: render
        env:
          REPO_URL: https://token:${{ github.token }}@github.com/${{ github.repository }}
          REPO_BRANCH: "main"
        with:
          json: ./apps.json

      - name: Load apps.json to environment
        run: echo "APPS_JSON_BASE64=$(base64 --wrap=0 ${{ steps.render.outputs.result }})" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v2
        with:
          push: true
          set: |
            *.args.APPS_JSON_BASE64=${{ env.APPS_JSON_BASE64 }}
